#ifndef THREADSAFETY_H
#define THREADSAFETY_H

#define LOCKABLE
#define SCOPED_LOCKABLE
#define EXCLUSIVE_LOCK_FUNCTION(...)

#define UNLOCK_FUNCTION(...)

#define EXCLUSIVE_TRYLOCK_FUNCTION(...)


#endif // THREADSAFETY_H
